# -*- coding: utf-8 -*-
"""Copia de notebook_01_texto_minilm_mongodb_atlas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuqFMiQvhV2AzpvltexnIo_OFDnjbtFE

# Notebook 01 · Texto con MiniLM + MongoDB Atlas Vector Search

Este notebook implementa la primera parte del proyecto en **MongoDB Atlas**:

- ingesta de documentos de texto
- chunking con varias estrategias
- embeddings con **MiniLM**
- carga en MongoDB Atlas
- creación de índices para búsqueda vectorial y filtros
- pruebas de recuperación semántica

> **Objetivo:** dejar lista la colección para que el notebook 02 pueda hacer retrieval top-k, construir contexto e integrar un LLM.

## 1. Instalación de dependencias
"""

!pip -q install pymongo[srv] sentence-transformers nltk pandas numpy scikit-learn openai

"""## 2. Imports y preparación

Cargamos librerías para:

- conexión con MongoDB Atlas
- embeddings con MiniLM
- procesamiento de texto
- análisis tabular
"""

import os
import re
import json
import math
import time
import getpass
import warnings
from typing import List, Dict, Optional, Tuple

import numpy as np
import pandas as pd
from pymongo import MongoClient, UpdateOne
from pymongo.errors import PyMongoError
from pymongo.operations import SearchIndexModel
from sentence_transformers import SentenceTransformer
import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

warnings.filterwarnings("ignore")
nltk.download("punkt", quiet=True)

"""## 3. Variables de conexión

Ingresa:

- `MONGODB_URI` de Atlas
- nombre de base de datos
- nombre de colección
"""

MONGODB_URI = getpass.getpass("MONGODB_URI de MongoDB Atlas: ").strip()
DB_NAME = input("Nombre de la base de datos [rag_texto_atlas]: ").strip() or "rag_texto_atlas"
COLLECTION_NAME = input("Nombre de la colección [documentos_texto]: ").strip() or "documentos_texto"

"""## 4. Conexión a MongoDB Atlas"""

client = MongoClient(MONGODB_URI)
db = client[DB_NAME]
collection = db[COLLECTION_NAME]

print("Base activa:", DB_NAME)
print("Colección activa:", COLLECTION_NAME)
print("Total documentos actuales:", collection.count_documents({}))

"""## 5. Modelo de embeddings

Usaremos `all-MiniLM-L6-v2`, que genera embeddings de 384 dimensiones.
"""

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIMENSIONS = 384

embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
print("Modelo cargado:", EMBEDDING_MODEL_NAME)

"""## 6. Corpus de ejemplo

Puedes reemplazar este corpus por el tuyo.  
Cada documento tiene un identificador, metadatos y el texto completo.
"""

corpus = [
    {
        "codigo_doc": "DOC001",
        "titulo": "Agricultura de precisión y toma de decisiones",
        "idioma": "es",
        "fecha": "2024-03-12",
        "fuente": "revista_agrotech",
        "contenido_texto": (
            "La agricultura de precisión integra sensores, imágenes satelitales y analítica de datos "
            "para mejorar la toma de decisiones en el campo. Permite optimizar el uso de agua, "
            "fertilizantes y pesticidas. También ayuda a identificar variaciones espaciales del cultivo "
            "y a reducir costos operativos."
        ),
    },
    {
        "codigo_doc": "DOC002",
        "titulo": "Analítica de datos para productividad agrícola",
        "idioma": "es",
        "fecha": "2024-05-18",
        "fuente": "informe_sectorial",
        "contenido_texto": (
            "La analítica de datos aplicada a la agricultura permite predecir rendimientos, "
            "monitorear enfermedades y hacer seguimiento al suelo. El uso de modelos predictivos "
            "facilita la planeación y mejora la productividad agrícola."
        ),
    },
    {
        "codigo_doc": "DOC003",
        "titulo": "Precision agriculture and smart irrigation",
        "idioma": "en",
        "fecha": "2024-06-01",
        "fuente": "smart_farming_journal",
        "contenido_texto": (
            "Precision agriculture combines remote sensing, IoT devices, and machine learning "
            "to improve irrigation and fertilization strategies. It supports site-specific management "
            "and can reduce waste while improving crop yield."
        ),
    }
]

df_docs = pd.DataFrame(corpus)
df_docs

"""## 7. Funciones de chunking

Implementamos tres estrategias:

- `fixed`: tamaño fijo aproximado por palabras
- `sentence`: respeta oraciones
- `semantic`: agrupa oraciones cercanas semánticamente
"""

def normalize_spaces(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def fixed_size_chunking(text: str, chunk_size: int = 80, overlap: int = 15) -> List[str]:
    words = normalize_spaces(text).split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + chunk_size, len(words))
        chunk = " ".join(words[start:end]).strip()
        if chunk:
            chunks.append(chunk)
        if end == len(words):
            break
        start = max(end - overlap, start + 1)
    return chunks


def sentence_aware_chunking(text: str, max_sentences: int = 3, overlap_sentences: int = 1) -> List[str]:
    sentences = [s.strip() for s in sent_tokenize(text) if s.strip()]
    print(sentences)
    chunks = []
    start = 0
    while start < len(sentences):
        end = min(start + max_sentences, len(sentences))
        chunk = " ".join(sentences[start:end]).strip()
        if chunk:
            chunks.append(chunk)
        if end == len(sentences):
            break
        start = max(end - overlap_sentences, start + 1)
    return chunks


def semantic_chunking(
    text: str,
    threshold: float = 0.78,
    min_sentences: int = 1,
    max_sentences: int = 4
) -> List[str]:
    sentences = [s.strip() for s in sent_tokenize(text) if s.strip()]
    if not sentences:
        return []

    if len(sentences) == 1:
        return sentences

    sent_embeddings = embedding_model.encode(sentences, normalize_embeddings=True)
    chunks = []
    current_chunk = [sentences[0]]

    for i in range(1, len(sentences)):
        sim = float(np.dot(sent_embeddings[i-1], sent_embeddings[i]))
        if sim >= threshold and len(current_chunk) < max_sentences:
            current_chunk.append(sentences[i])
        else:
            if len(current_chunk) >= min_sentences:
                chunks.append(" ".join(current_chunk))
            current_chunk = [sentences[i]]

    if current_chunk:
        chunks.append(" ".join(current_chunk))

    return chunks


STRATEGIES = {
    "fixed": fixed_size_chunking,
    "sentence": sentence_aware_chunking,
    "semantic": semantic_chunking,
}

"""## 8. Comparación rápida de chunking sobre un documento"""

sample_text = corpus[0]["contenido_texto"]

for name, fn in STRATEGIES.items():
    print(f"\n=== Estrategia: {name} ===")
    chunks = fn(sample_text)
    for idx, ch in enumerate(chunks, start=1):
        print(f"[{idx}] {ch}")

"""## 9. Construcción del dataset de chunks

Transformamos cada documento en múltiples chunks y agregamos metadatos:
- `codigo_doc`
- `titulo`
- `idioma`
- `fuente`
- `chunk_id`
- `estrategia_chunking`
"""

def build_chunk_records(documents: List[Dict]) -> pd.DataFrame:
    rows = []
    for doc in documents:
        for strategy_name, chunk_fn in STRATEGIES.items():
            chunks = chunk_fn(doc["contenido_texto"])
            for idx, chunk_text in enumerate(chunks):
                rows.append({
                    "codigo_doc": doc["codigo_doc"],
                    "titulo": doc["titulo"],
                    "idioma": doc["idioma"],
                    "fecha": doc["fecha"],
                    "fuente": doc["fuente"],
                    "contenido_texto": doc["contenido_texto"],
                    "chunk_id": idx,
                    "estrategia_chunking": strategy_name,
                    "texto_chunk": chunk_text,
                    "n_chars": len(chunk_text),
                })
    return pd.DataFrame(rows)

df_chunks = build_chunk_records(corpus)
df_chunks.head(10)

"""## 10. Generación de embeddings para cada chunk"""

def embed_texts(texts: List[str], batch_size: int = 32) -> np.ndarray:
    return embedding_model.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=True,
        normalize_embeddings=True
    )

chunk_embeddings = embed_texts(df_chunks["texto_chunk"].tolist())
chunk_embeddings.shape

"""## 11. Preparación de documentos para MongoDB

Guardamos un documento por chunk.  
Cada documento contiene:

- metadatos del documento fuente
- texto del chunk
- embedding
"""

atlas_docs = []
for row, emb in zip(df_chunks.to_dict(orient="records"), chunk_embeddings):
    row["embedding"] = [float(x) for x in emb]
    row["n_tokens_aprox"] = max(1, math.ceil(len(row["texto_chunk"].split()) * 1.1))
    atlas_docs.append(row)

atlas_docs[0]

"""## 12. Carga en MongoDB Atlas

Usamos `upsert` por combinación de:
- `codigo_doc`
- `estrategia_chunking`
- `chunk_id`

Así puedes reejecutar el notebook sin duplicar chunks.
"""

def load_chunks_to_mongodb(collection, docs: List[Dict]):
    ops = []
    for doc in docs:
        filt = {
            "codigo_doc": doc["codigo_doc"],
            "estrategia_chunking": doc["estrategia_chunking"],
            "chunk_id": doc["chunk_id"],
        }
        ops.append(
            UpdateOne(
                filt,
                {"$set": doc},
                upsert=True
            )
        )

    if not ops:
        return None

    result = collection.bulk_write(ops, ordered=False)
    return result

result = load_chunks_to_mongodb(collection, atlas_docs)
print(result.bulk_api_result if result else "Sin operaciones")
print("Total documentos en colección:", collection.count_documents({}))

"""## 13. Creación de índices

Crearemos:
- índice clásico para filtros y trazabilidad
- índice de **MongoDB Vector Search**

> Si tu driver o plan no permite crear el índice por código, puedes usar la definición mostrada y crearla en el panel de Atlas.
"""

# Índices clásicos
collection.create_index("codigo_doc")
collection.create_index("estrategia_chunking")
collection.create_index("idioma")
collection.create_index("fecha")

VECTOR_INDEX_NAME = "vector_index_texto"

vector_index_definition = {
    "fields": [
        {
            "type": "vector",
            "path": "embedding",
            "numDimensions": EMBEDDING_DIMENSIONS,
            "similarity": "cosine"
        },
        {
            "type": "filter",
            "path": "estrategia_chunking"
        },
        {
            "type": "filter",
            "path": "idioma"
        },
        {
            "type": "filter",
            "path": "codigo_doc"
        }
    ]
}

print("Definición del índice vectorial:")
print(json.dumps(vector_index_definition, indent=2))

try:
    search_model = SearchIndexModel(
        definition=vector_index_definition,
        name=VECTOR_INDEX_NAME,
        type="vectorSearch"
    )
    created_name = collection.create_search_index(model=search_model)
    print("Solicitud de creación de índice enviada:", created_name)
except Exception as e:
    print("No se pudo crear el índice por código.")
    print("Crea manualmente un índice Vector Search en Atlas con esta definición.")
    print("Detalle:", e)

"""## 14. Espera opcional para indexado

Los índices de Atlas pueden tardar un poco en quedar listos.
"""

INDEX_READY_WAIT_SECONDS = 10
print(f"Esperando {INDEX_READY_WAIT_SECONDS} segundos por si Atlas aún está indexando...")
time.sleep(INDEX_READY_WAIT_SECONDS)
print("Continuando.")

"""## 15. Funciones de búsqueda semántica

Usaremos `$vectorSearch` para recuperar los chunks más cercanos semánticamente.
"""

def embed_query(question: str) -> List[float]:
    return embedding_model.encode(question, normalize_embeddings=True).tolist()


def search_top_k(
    collection,
    question_vector: List[float],
    top_k: int = 5,
    strategy: Optional[str] = None,
    idioma: Optional[str] = None,
    num_candidates: int = 100
) -> pd.DataFrame:
    vector_stage = {
        "$vectorSearch": {
            "index": VECTOR_INDEX_NAME,
            "path": "embedding",
            "queryVector": question_vector,
            "numCandidates": max(num_candidates, top_k),
            "limit": top_k
        }
    }

    filters = []
    if strategy:
        filters.append({"estrategia_chunking": {"$eq": strategy}})
    if idioma:
        filters.append({"idioma": {"$eq": idioma}})
    if filters:
        vector_stage["$vectorSearch"]["filter"] = {"$and": filters} if len(filters) > 1 else filters[0]

    pipeline = [
        vector_stage,
        {
            "$project": {
                "_id": 0,
                "codigo_doc": 1,
                "titulo": 1,
                "idioma": 1,
                "fecha": 1,
                "fuente": 1,
                "chunk_id": 1,
                "estrategia_chunking": 1,
                "texto_chunk": 1,
                "score": {"$meta": "vectorSearchScore"}
            }
        }
    ]

    rows = list(collection.aggregate(pipeline))
    return pd.DataFrame(rows)

"""## 16. Prueba de búsqueda semántica

Cambia la consulta y observa:
- qué chunks recupera
- cómo cambia el score
- qué estrategia funciona mejor
"""

query = "beneficios del uso de tecnología para mejorar decisiones en el campo"
query_vector = embed_query(query)

df_results = search_top_k(
    collection=collection,
    question_vector=query_vector,
    top_k=5,
    strategy=None,
    idioma=None
)

df_results

"""## 17. Construcción de contexto base para el siguiente notebook

Este bloque deja lista una función simple para convertir resultados en contexto.
"""

def build_context_from_results(df_results: pd.DataFrame, max_chars: int = 2500) -> str:
    blocks = []
    current_len = 0

    if df_results is None or df_results.empty:
        return ""

    for i, row in df_results.iterrows():
        block = (
            f"[Fragmento {i+1}]\n"
            f"Documento: {row['titulo']}\n"
            f"Idioma: {row['idioma']}\n"
            f"Estrategia: {row['estrategia_chunking']}\n"
            f"Score: {float(row['score']):.4f}\n"
            f"Contenido:\n{row['texto_chunk']}"
        )

        if current_len + len(block) > max_chars:
            break

        blocks.append(block)
        current_len += len(block) + 2

    return "\n\n".join(blocks)

print(build_context_from_results(df_results, max_chars=1200))

"""## 18. Comparación básica entre estrategias para una misma consulta"""

question = "beneficios del uso de tecnología para mejorar decisiones en el campo"

comparacion = []
for strategy in STRATEGIES.keys():
    df_tmp = search_top_k(
        collection=collection,
        question_vector=embed_query(question),
        top_k=3,
        strategy=strategy,
        idioma=None
    )
    if not df_tmp.empty:
        comparacion.append({
            "estrategia": strategy,
            "mejor_score": float(df_tmp.iloc[0]["score"]),
            "top1_titulo": df_tmp.iloc[0]["titulo"],
            "top1_chunk": df_tmp.iloc[0]["texto_chunk"][:120] + "..."
        })

pd.DataFrame(comparacion)

"""## 19. Inspección rápida de la colección

Puedes revisar algunos documentos cargados.
"""

sample_docs = list(collection.find({}, {
    "_id": 0,
    "codigo_doc": 1,
    "titulo": 1,
    "estrategia_chunking": 1,
    "chunk_id": 1,
    "texto_chunk": 1
}).limit(5))

pd.DataFrame(sample_docs)