# -*- coding: utf-8 -*-
"""Copia de notebook_02_recuperacion_topk_contexto_llm_mongodb_atlas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvtveRsXTsg2-F_T3D-8knMYyEESxNX1

# Notebook 02 · Recuperación top-k, construcción de contexto e integración con LLM en MongoDB Atlas

Este notebook continúa el flujo del notebook 01, pero ahora sobre **MongoDB Atlas Vector Search**:

- recuperación `top-k`
- construcción de contexto
- integración con un LLM
- persistencia de consultas y respuestas
- comparación de estrategias de chunking

## 1. Instalación de dependencias
"""

!pip -q install pymongo[srv] sentence-transformers openai pandas nltk

"""## 2. Importaciones y configuración inicial"""

import os
import json
import time
import getpass
import textwrap
from typing import List, Dict, Optional

import pandas as pd
import nltk
from pymongo import MongoClient
from sentence_transformers import SentenceTransformer
from openai import OpenAI

nltk.download("punkt", quiet=True)

"""## 3. Variables de conexión

Ingresa:

- `MONGODB_URI`
- nombre de base de datos
- colección de chunks
- `GROQ_API_KEY` si vas a usar Groq
"""

MONGODB_URI = getpass.getpass("MONGODB_URI de MongoDB Atlas: ").strip()
DB_NAME = input("Nombre de la base de datos [rag_texto_atlas]: ").strip() or "rag_texto_atlas"
CHUNKS_COLLECTION_NAME = input("Colección de chunks [documentos_texto]: ").strip() or "documentos_texto"
QUERY_LOG_COLLECTION_NAME = input("Colección de consultas [consultas_rag]: ").strip() or "consultas_rag"
RESULTS_COLLECTION_NAME = input("Colección de resultados [resultados_rag]: ").strip() or "resultados_rag"

GROQ_API_KEY = getpass.getpass("GROQ_API_KEY (o Enter para omitir): ").strip()
LLM_BASE_URL = input("Base URL OpenAI-compatible [https://api.groq.com/openai/v1]: ").strip() or "https://api.groq.com/openai/v1"
LLM_MODEL = input("Modelo LLM [llama-3.3-70b-versatile]: ").strip() or "llama-3.3-70b-versatile"

"""## 4. Conexión a MongoDB Atlas y carga del modelo MiniLM"""

client = MongoClient(MONGODB_URI)
db = client[DB_NAME]
chunks_collection = db[CHUNKS_COLLECTION_NAME]
queries_collection = db[QUERY_LOG_COLLECTION_NAME]
results_collection = db[RESULTS_COLLECTION_NAME]

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
VECTOR_INDEX_NAME = "vector_index_texto"

embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

print("Base:", DB_NAME)
print("Colección chunks:", CHUNKS_COLLECTION_NAME, "→", chunks_collection.count_documents({}), "docs")
print("Colección consultas:", QUERY_LOG_COLLECTION_NAME)
print("Colección resultados:", RESULTS_COLLECTION_NAME)

"""## 5. Verificación rápida de colecciones

Este notebook asume que el notebook 01 ya cargó chunks en la colección principal.
"""

status_rows = []
for name in [CHUNKS_COLLECTION_NAME, QUERY_LOG_COLLECTION_NAME, RESULTS_COLLECTION_NAME]:
    try:
        status_rows.append({"coleccion": name, "conteo": db[name].count_documents({})})
    except Exception as e:
        status_rows.append({"coleccion": name, "conteo": f"ERROR: {e}"})

pd.DataFrame(status_rows)

"""## 6. Funciones utilitarias"""

def embed_query(question: str) -> List[float]:
    return embedding_model.encode(question, normalize_embeddings=True).tolist()


def search_top_k(
    collection,
    question_vector: List[float],
    top_k: int = 5,
    strategy: Optional[str] = None,
    idioma: Optional[str] = None,
    fecha_desde: Optional[str] = None,
    fecha_hasta: Optional[str] = None,
    num_candidates: int = 100
) -> pd.DataFrame:
    filters = []
    if strategy:
        filters.append({"estrategia_chunking": {"$eq": strategy}})
    if idioma:
        filters.append({"idioma": {"$eq": idioma}})
    if fecha_desde or fecha_hasta:
        date_filter = {}
        if fecha_desde:
            date_filter["$gte"] = fecha_desde
        if fecha_hasta:
            date_filter["$lte"] = fecha_hasta
        filters.append({"fecha": date_filter})

    vector_stage = {
        "$vectorSearch": {
            "index": VECTOR_INDEX_NAME,
            "path": "embedding",
            "queryVector": question_vector,
            "numCandidates": max(num_candidates, top_k),
            "limit": top_k
        }
    }
    if filters:
        vector_stage["$vectorSearch"]["filter"] = {"$and": filters} if len(filters) > 1 else filters[0]

    pipeline = [
        vector_stage,
        {
            "$project": {
                "_id": 0,
                "codigo_doc": 1,
                "titulo": 1,
                "idioma": 1,
                "fecha": 1,
                "fuente": 1,
                "chunk_id": 1,
                "estrategia_chunking": 1,
                "texto_chunk": 1,
                "score": {"$meta": "vectorSearchScore"}
            }
        }
    ]
    return pd.DataFrame(list(collection.aggregate(pipeline)))


def build_context(
    retrieved_df: pd.DataFrame,
    max_chars: int = 5000,
    include_metadata: bool = True
) -> str:
    if retrieved_df is None or retrieved_df.empty:
        return ""

    blocks = []
    total_chars = 0

    for i, row in retrieved_df.iterrows():
        if include_metadata:
            block = (
                f"[Fragmento {i+1}]\n"
                f"Documento: {row['titulo']}\n"
                f"Idioma: {row['idioma']}\n"
                f"Fecha: {row['fecha']}\n"
                f"Fuente: {row['fuente']}\n"
                f"Estrategia: {row['estrategia_chunking']}\n"
                f"Score: {float(row['score']):.4f}\n"
                f"Contenido:\n{row['texto_chunk']}"
            )
        else:
            block = f"[Fragmento {i+1}]\n{row['texto_chunk']}"

        if total_chars + len(block) > max_chars:
            break

        blocks.append(block)
        total_chars += len(block) + 2

    return "\n\n".join(blocks)


def get_llm_client(api_key: str, base_url: str = LLM_BASE_URL):
    if not api_key:
        raise ValueError("No se proporcionó API key para el LLM.")
    return OpenAI(api_key=api_key, base_url=base_url)


def answer_with_llm(
    client: OpenAI,
    question: str,
    context: str,
    model: str = LLM_MODEL,
    temperature: float = 0.2,
    max_tokens: int = 700
) -> str:
    system_prompt = (
        "Eres un asistente RAG preciso, conservador y académico. "
        "Debes responder únicamente con base en el contexto recuperado. "
        "Si el contexto no es suficiente, dilo explícitamente. "
        "No inventes datos, no cites fuentes inexistentes y separa claramente "
        "lo que está soportado por el contexto de cualquier inferencia moderada."
    )

    user_prompt = f'''
Pregunta del usuario:
{question}

Contexto recuperado:
{context}

Instrucciones:
- Responde en español.
- Usa una redacción clara y estructurada.
- Si hay vacíos de información, indícalo.
- Cuando sea útil, menciona el título del documento del que proviene el contexto.
'''

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content

"""## 7. Persistencia de consultas y resultados en MongoDB"""

def ensure_logging_indexes():
    queries_collection.create_index("fecha")
    results_collection.create_index("fecha")
    results_collection.create_index("id_consulta")
    results_collection.create_index("question")


def save_query_and_results(
    question: str,
    retrieved_df: pd.DataFrame,
    answer: Optional[str] = None,
    metadata: Optional[dict] = None
) -> str:
    ensure_logging_indexes()
    metadata = metadata or {}

    query_doc = {
        "question": question,
        "fecha": pd.Timestamp.utcnow().isoformat(),
        "metadata": metadata
    }
    query_insert = queries_collection.insert_one(query_doc)
    id_consulta = str(query_insert.inserted_id)

    retrieval_docs = []
    if retrieved_df is not None and not retrieved_df.empty:
        for rank, row in enumerate(retrieved_df.to_dict(orient="records"), start=1):
            retrieval_docs.append({
                "id_consulta": id_consulta,
                "fecha": pd.Timestamp.utcnow().isoformat(),
                "tipo": "retrieval",
                "question": question,
                "ranking": rank,
                "codigo_doc": row.get("codigo_doc"),
                "chunk_id": row.get("chunk_id"),
                "titulo": row.get("titulo"),
                "estrategia_chunking": row.get("estrategia_chunking"),
                "score": float(row.get("score", 0.0)),
                "texto_chunk": row.get("texto_chunk"),
            })

    if retrieval_docs:
        results_collection.insert_many(retrieval_docs)

    if answer is not None and str(answer).strip():
        results_collection.insert_one({
            "id_consulta": id_consulta,
            "fecha": pd.Timestamp.utcnow().isoformat(),
            "tipo": "respuesta_rag",
            "question": question,
            "answer": answer,
            "metadata": metadata
        })

    return id_consulta

"""## 8. Pipeline completo RAG"""

def rag_pipeline(
    question: str,
    top_k: int = 5,
    strategy: Optional[str] = None,
    idioma: Optional[str] = None,
    fecha_desde: Optional[str] = None,
    fecha_hasta: Optional[str] = None,
    max_context_chars: int = 5000,
    use_llm: bool = True
) -> Dict:
    qvec = embed_query(question)

    retrieved = search_top_k(
        collection=chunks_collection,
        question_vector=qvec,
        top_k=top_k,
        strategy=strategy,
        idioma=idioma,
        fecha_desde=fecha_desde,
        fecha_hasta=fecha_hasta
    )

    context = build_context(
        retrieved_df=retrieved,
        max_chars=max_context_chars,
        include_metadata=True
    )

    answer = None
    if use_llm:
        if not context.strip():
            answer = "No se recuperó contexto suficiente para responder la pregunta."
        else:
            client_llm = get_llm_client(GROQ_API_KEY, LLM_BASE_URL)
            answer = answer_with_llm(client_llm, question, context)

    query_id = save_query_and_results(
        question=question,
        retrieved_df=retrieved,
        answer=answer,
        metadata={
            "top_k": top_k,
            "strategy": strategy,
            "idioma": idioma,
            "fecha_desde": fecha_desde,
            "fecha_hasta": fecha_hasta
        }
    )

    return {
        "id_consulta": query_id,
        "question": question,
        "retrieved": retrieved,
        "context": context,
        "answer": answer
    }

"""## 9. Prueba de recuperación top-k"""

test_question = "¿Qué beneficios tiene usar tecnología y analítica de datos en el campo?"
df_test = search_top_k(
    collection=chunks_collection,
    question_vector=embed_query(test_question),
    top_k=5
)
df_test

"""## 10. Construcción del contexto"""

context_preview = build_context(df_test, max_chars=2200, include_metadata=True)
print(context_preview)

"""## 11. Integración con el LLM"""

if GROQ_API_KEY:
    client_llm = get_llm_client(GROQ_API_KEY, LLM_BASE_URL)
    answer_preview = answer_with_llm(
        client=client_llm,
        question=test_question,
        context=context_preview
    )
    print(answer_preview)
else:
    print("No se proporcionó GROQ_API_KEY. Este bloque se omite.")

"""## 12. Pipeline completo RAG"""

result = rag_pipeline(
    question="Resume qué aporta la agricultura de precisión y menciona dos beneficios concretos.",
    top_k=5,
    strategy=None,
    idioma=None,
    max_context_chars=4500,
    use_llm=bool(GROQ_API_KEY)
)

print("ID consulta:", result["id_consulta"])
print("\n=== RESPUESTA ===\n")
print(result["answer"] if result["answer"] else "[Sin llamada al LLM]")

"""## 13. Ver los fragmentos recuperados"""

result["retrieved"]

"""## 14. Explorar qué quedó guardado"""

print("=== Últimas consultas ===")
display(pd.DataFrame(list(
    queries_collection.find({}, {"question": 1, "fecha": 1, "metadata": 1}).sort("fecha", -1).limit(5)
)))

print("\n=== Últimos resultados ===")
display(pd.DataFrame(list(
    results_collection.find({}, {"tipo": 1, "question": 1, "ranking": 1, "titulo": 1, "score": 1, "answer": 1, "fecha": 1}).sort("fecha", -1).limit(10)
)))

"""## 15. Comparar estrategias de chunking"""

question_compare = "¿Cómo ayuda la tecnología a mejorar decisiones en agricultura?"
comparison = []

for strategy in ["fixed", "sentence", "semantic"]:
    tmp = search_top_k(
        collection=chunks_collection,
        question_vector=embed_query(question_compare),
        top_k=3,
        strategy=strategy
    )
    if not tmp.empty:
        comparison.append({
            "estrategia": strategy,
            "top1_score": float(tmp.iloc[0]["score"]),
            "top1_titulo": tmp.iloc[0]["titulo"],
            "top1_chunk": tmp.iloc[0]["texto_chunk"][:120] + "..."
        })

pd.DataFrame(comparison)

"""## 16. Función práctica para preguntas rápidas"""

def ask(question: str, top_k: int = 5, strategy: Optional[str] = None, idioma: Optional[str] = None):
    result = rag_pipeline(
        question=question,
        top_k=top_k,
        strategy=strategy,
        idioma=idioma,
        use_llm=bool(GROQ_API_KEY)
    )
    print("\n=== RESPUESTA ===\n")
    print(result["answer"] if result["answer"] else "[Sin llamada al LLM]")
    return result

# Ejemplo:
# r = ask("¿Qué relación existe entre analítica de datos y toma de decisiones?", top_k=4, strategy="semantic")

"""## 17. Siguientes extensiones

Sobre este notebook, el paso siguiente natural es:

1. añadir evaluación con **RAGAS**
2. incorporar búsqueda híbrida (`$vectorSearch` + `$search`)
3. extender a imágenes con CLIP
"""